name: 🐛 Bug Report
description: Create a bug report to help us improve.
title: "🐛 [Bug Report]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Hello and thanks for taking the time to fill out this bug report!

        Before you begin, **please ensure there are no existing open or closed issue related your report**.

        ---

  - type: input
    id: cms-version
    attributes:
      label: BlizzCMS Version
      description: e.g. 1.1.0
    validations:
      required: true
  - type: dropdown
    id: emulator
    attributes:
      label: Emulator
      description: Which emulator are you using?
      options:
        - AzerothCore
        - CMaNGOS
        - MaNGOS
        - TrinityCore
        - Other
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP do you use?
      options:
        - PHP 7.4
        - PHP 8.0
        - PHP 8.1
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: dropdown
    id: web-server
    attributes:
      label: Web server
      description: What web server are you using?
      options:
        - Apache
        - Nginx
        - Other
    validations:
      required: true
  - type: input
    id: database
    attributes:
      label: Database
      description: e.g. MySQL 5.7, MariaDB 10.6
    validations:
      required: false
  - type: textarea
    id: current
    attributes:
      label: Description
      description: Describe the bug in detail. We need information in order to solve the problem.
  - type: textarea
    id: reproduce
    attributes:
      label: How can I reproduce the problem?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: You can drag the images here to upload or share the links.
